name: mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  http: ^1.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  timeago: ^3.7.1
  image_picker: ^1.1.2
  file_picker: ^8.3.4
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3
  cryptography: ^2.7.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
